# Generated by Django 5.1.1 on 2024-09-19 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DF', max_length=2)),
                ('reading_time', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('WS', 'Website'), ('RO', 'Robot'), ('SS', 'Security'), ('PL', 'Programming Language'), ('DE', 'Developer'), ('NN', 'Networking'), ('IO', 'IOT'), ('AI', 'Artificial Intelligence'), ('TE', 'Technology')], default='WS', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['published'], name='blog_post_publish_8fcab7_idx')],
            },
        ),
    ]
