# Generated by Django 5.1 on 2025-01-28 18:05

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('وبسایت', 'وبسایت'), ('رباتیک', 'رباتیک'), ('امنیت', 'امنیت'), ('زبان برنامه نویسی', 'زبان برنامه نویسی'), ('توسعه دهنده', 'توسعه دهنده'), ('شبکه', 'شبکه'), ('اینترنت اشیا', 'اینترنت اشیا'), ('هوش مصنوعی', 'هوش مصنوعی'), ('تکلونوژی', 'تکلونوژی')], default='وبسایت', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=200),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('imag_file', django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='post_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='blog_image_created_1ba45b_idx')],
            },
        ),
    ]
